### ISSUE TITLE
Unsure about how to edit user_constants.py

### ISSUE THREAD

**Issue by ghost** [MadryLab/robust_representations#1]
`Edit user_constants.py to point to PyTorch-formatted versions of the CIFAR and ImageNet datasets.`
What is the right way to point to the dataset(s)?

**Comment by hcl14** [comment]
For a quick start, I have downloaded and extracted tiny imagenet `wget http://cs231n.stanford.edu/tiny-imagenet-200.zip` into `tiny-imagenet/tiny-imagenet-200` subfolder containing train, test, val folders. Validation folder needs to have the same structure as train. i.e. `val/something/images`, so I just copied and renamed train. My `user_constants.py` has record:

`'RestrictedImageNet': '/home/hcl/Documents/projects/robust_representations/tiny-imagenet/tiny-imagenet-200'`

**Comment by andrewilyas** [comment]
Hi all! So for CIFAR, simply doing the following in a python shell should work, replacing PATH with where you want to store CIFAR:
```python
import torch
import torchvision
import torchvision.transforms as transforms
transform = transforms.ToTensor()
torchvision.datasets.CIFAR10(root=PATH, train=True, download=True, transform=transform)
```

For ImageNet, we use the real (not Tiny) ImageNet dataset, so you'll need to download it and then use something like https://raw.githubusercontent.com/soumith/imagenetloader.torch/master/valprep.sh to put it into pytorch format.

**Comment by shreyapuranik** [comment]
I am using this code for one of my projects. I am having a lot of trouble with this aspect, with the user_constants part, and I was hoping to get some help with implementing and setting this up! Thank you in advance

**Comment by dtsip** [comment]
The only thing you need to do in that file is replace the paths you care about to point to the corresponding dataset directory (also see thread above). What exactly are you having trouble with?
