### ISSUE TITLE
PGD Configuration about l2 adversarial training of Restricted ImageNet

### ISSUE THREAD

**Issue by msingh27** [MadryLab/robust_representations#4]
Hi,

As mentioned in table 3, it says to use 7 step PGD with eps 3.5 and step size=0.1 for adv l2 training.

But with 7 steps and step size=0.1, the adv_image will be 0.7 l2 distance apart from the original image. 

Can you also comment on the image pixel range (ie is it from [-1,1] or [0,1] and the config for the optimizer?

**Comment by andrewilyas** [comment]
That is a typo! It should be 7 step PGD with step size 0.5.

The pixel range is [0, 1], and the optimizer is SGD---see appendix A.2 in the paper for all the hyper-parameters.
