### ISSUE TITLE
Instructions for training a robust neural network

### ISSUE THREAD

**Issue by GlebSBrykin** [MadryLab/robust_representations#5]
Good day! You have a wonderful and very useful project, but I would like to get a more specific description of the learning process of the neural network robust. In the context of Your source code. Can you write instructions on how to train an arbitrary neural network on an arbitrary dataset? For example VGG16 or VGG19 on Places365?

**Comment by andrewilyas** [comment]
Hi! You may be interested in the ``robustness`` library that we released, which allows you to do exactly this and has detailed documentation and tutorials. All the notebooks here are actually based on this library.

Code: https://github.com/MadryLab/robustness
Docs: https://robustness.readthedocs.io
