### ISSUE TITLE
Unreadable JSON error

### ISSUE THREAD

**Issue by MehdiAbbanaBennani** [MadryLab/robust_representations#6]
Hello ! 
Thanks for the great work ! 
I have been running into a Not JSON Error regarding the "maximizing_inputs.ipynb" file. 
Could you please let me know how to fix the error ?
Thanks,

**Comment by andrewilyas** [comment]
Hi! Can you please give some more detail about the error, including exactly what you are running to get the error as well as the full stack trace?

**Comment by MehdiAbbanaBennani** [comment]
The full stack trace is :
`Unreadable Notebook: /home/mehdia/research/reasoning/code/robust_representations/maximizing_inputs.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n {\\n "cell_type": "c...',)`

I get the error as soon as I try to open "maximizing_inputs.ipynb" through jupyter.

**Comment by sherdencooper** [comment]
I met the same issue about "maximizing_inputs.ipynb" file , have you solved this problem?

**Comment by dtsip** [comment]
Should be fixed. Reopen if bug persists.
