### ISSUE TITLE
robust model training details

### ISSUE THREAD

**Issue by sherdencooper** [MadryLab/robust_representations#8]
Hi, your paper is really interesting! I am reproducing your experiments with both robustness package and my own codes. Can you provide more details about how to adversarially training the robust model you provided? Specifically, I want to know eps, steps, step size, attack-lr and adversarial algorithm you used to train the model so I can compare the inversion performance between my own codes and your robustness package. Thx a lot in advance.

**Comment by dtsip** [comment]
Hi, the training details can be found in Tables 2 and 3 of the paper. Specifically, we used eps=3 (in L2-norm), 7 steps, attack-lr=0.5, and training step size of 0.1 with a 10x drop at epoch 30 and 60. We performed adversarial training with standard PGD.

**Comment by DuyguSerbes** [comment]
Hello, in the paper I cannot find the parameters of CIFAR-10 pretrained [model](http://andrewilyas.com/CIFAR.pt). Could you please share the parameters used for this model or where can I find them? Thanks in advance.
